<?php
define('RVK_TICKETING_SERVICE_DESK_OPENING_HOURS', variable_get('rvk_ticketing_service_desk_opening_hours'));
define('RVK_TICKETING_SERVICE_DESK_OPENING_HOUR', variable_get('rvk_ticketing_service_desk_opening_hours'));
define('RVK_TICKETING_SERVICE_DESK_OPENING_MINUTE', variable_get('rvk_ticketing_service_desk_opening_minute'));
define('RVK_TICKETING_SERVICE_DESK_DURATION', variable_get('rvk_ticketing_service_desk_duration'));
define('RVK_TICKETING_SERVICE_DESK_DAYS_TO_RESPOND', variable_get('rvk_ticketing_service_desk_days_to_respond'));

/**
 * MODULE FILE
 */

/**
 * Implements hook_menu().
 */
function rvk_ticketing_menu() {
  $items['abendingar/senda-inn-abendingu'] = [
    'title' => 'Senda inn ábendingu',
    'page callback' => 'rvk_ticketing_create_indication_page',
    'access arguments' => ['view ticketing content'],
  ];

  $items['abendingar/breyta-abendingu/%'] = [
    'title' => 'Breyta ábendingu',
    'page callback' => 'rvk_ticketing_edit_indication_page',
    'access arguments' => ['edit ticketing content'],
    'page arguments' => array(2),
    'file' => 'includes/indication_edit.inc',
    'file path' => drupal_get_path('module', 'rvk_ticketing'),
  ];

  $items['admin/config/services/abendingar'] = array(
    'title' => t('Ábendingar config'),
    'description' => 'Misc settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rvk_ticketing_admin'),
    'file' => 'rvk_ticketing.admin.inc',
    'file path' => drupal_get_path('module', 'rvk_ticketing'),
    'access arguments' => array('administer ticketing settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['debug'] = [
    'title' => t('Debug page'),
    'description' => 'Debug page',
    'page callback' => 'rvk_ticketing_debug',
    'access arguments' => ['access content'],
  ];

  return $items;
}

function rvk_ticketing_debug() {

}

/**
 * Implements form_alter().
 */
function rvk_ticketing_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'indications_node_form') {

    $form['#attached']['css'] = [
      'https://js.arcgis.com/3.13/esri/css/esri.css' => [
        'type' => 'external',
      ],
      drupal_get_path('module', 'rvk_ticketing') . '/css/geolocation.css',
      drupal_get_path('module', 'rvk_ticketing') . '/css/edit_indication_form_styles.css',
    ];

    if(isset($form['#node'])) {
      if(is_object($form['#node'])) {
        //Disables the fields that should not be shown (eg. editable)
        $form['field_indication_text']['#access'] = FALSE;
        $form['field_indication_position_x']['#access'] = FALSE;
        $form['field_indication_position_y']['#access'] = FALSE;
        $form['field_indication_location']['#access'] = FALSE;
        $form['field_indication_respond_by']['#access'] = FALSE;
        $form['field_indication_responded_at']['#access'] = FALSE;
        $form['field_indication_close_by']['#access'] = FALSE;
        $form['field_indication_closed_at']['#access'] = FALSE;

        //Create the indication text markup, to display what the original indication said and change the sort order
        //of the fields
        $form['title']['#weight'] = -20;
        $form['field_interpered_indication_text']['#weight'] = 100;
        $form['field_response']['#weight'] = 200;
        $form['field_indication_text_markup']['#weight'] = 20;
        $form['field_indication_text_markup']['#markup'] =
          '<div class="indication-text-readonly"><label class="control-label">Ábending</label><div><p>' . $form['#node']->field_indication_text[LANGUAGE_NONE][0]['value'] . "</p></div></div>";

        //Moves the markup into the fieldset group_indication_content
        $form['#group_children']['field_indication_text_markup'] = "group_indication_content";

        //The map and location
        if($coords_set = isset($form['#node']->field_indication_position_x[LANGUAGE_NONE][0])) {
          $xcoord = $form['#node']->field_indication_position_x[LANGUAGE_NONE][0]['value'];
          $ycoord = $form['#node']->field_indication_position_y[LANGUAGE_NONE][0]['value'];
          $form['coords_markup']['#markup'] = '<div class="location-text-readonly"><label class="control-label">X og Y hnit</label><p>X: ' . $xcoord . ' Y: ' . $ycoord . '</p></div>';
          $form['#group_children']['coords_markup'] = "group_indication_media_items";

          $coords = [
            'xcoord' => $xcoord,
            'ycoord' => $ycoord,
          ];

          drupal_add_js($coords, 'setting');
        }
        if($location_set = isset($form['#node']->field_indication_location[LANGUAGE_NONE][0])) {
          $form['location_markup']['#markup'] = "<div class=\"location-text-readonly\"><label class=\"control-label\">Staðsetning</label><p>" . $form['#node']->field_indication_location[LANGUAGE_NONE][0]['value'] . "</p></div>";
          $form['#group_children']['location_markup'] = "group_indication_media_items";
        }

        $form['map_markup']['#weight'] = 16;
        $form['map_markup']['#markup'] = '<div class="map-markup"><label class="control-label">Kort</label><div id="mapDiv" style="max-width: 920px"></div></div>';

        //Moves the markup into the fieldset group_indication_content
        $form['#group_children']['map_markup'] = "group_indication_media_items";

        $form['created_markup']['#weight'] = 39;
        $form['created_markup']['#markup'] = "<div class=\"response-by-time-readonly\"><label class=\"control-label\">Ábending barst</label><p>" . strftime('%d. %B %Y klukkan %H:%M', $form['#node']->created) . "</p> </p></div>";
        $form['#group_children']['created_markup'] = "group_indication_timestamps";

        $form['respond_by_markup']['#weight'] = 40;
        $form['respond_by_markup']['#markup'] = "<div class=\"response-time-readonly\"><label class=\"control-label\">Svara þarf fyrir</label><p>" . strftime('%d. %B %Y klukkan %H:%M', $form['#node']->field_indication_respond_by[LANGUAGE_NONE][0]['value']) . "</p> </p></div>";
        $form['#group_children']['respond_by_markup'] = "group_indication_timestamps";

        if(isset($form['#node']->field_indication_responded_at[LANGUAGE_NONE][0])) {
          $form['responded_at_markup']['#weight'] = 41;
          $form['responded_at_markup']['#markup'] = "<div class=\"response-time-readonly\"><label class=\"control-label\">Ábendingunni var svarað þann</label><p>" . strftime('%d. %B %Y klukkan %H:%M', $form['#node']->field_indication_responded_at[LANGUAGE_NONE][0]['value']) . "</p> </p></div>";
          $form['#group_children']['responded_at_markup'] = "group_indication_timestamps";
        }

        if(isset($form['#node']->field_indication_close_by[LANGUAGE_NONE][0])) {
          $form['close_by_markup']['#weight'] = 42;
          $form['close_by_markup']['#markup'] = "<div class=\"closing-time-readonly\"><label class=\"control-label\">Ljúka þarf ábendingunni fyrir</label><p>" . strftime('%d. %B %Y klukkan %H:%M', $form['#node']->field_indication_close_by[LANGUAGE_NONE][0]['value']) . "</p> </p></div>";
          $form['#group_children']['close_by_markup'] = "group_indication_timestamps";
        }

        if(isset($form['#node']->field_indication_closed_at[LANGUAGE_NONE][0])) {
          $form['closed_at_markup']['#weight'] = 43;
          $form['closed_at_markup']['#markup'] = "<div class=\"closing-time-readonly\"><label class=\"control-label\">Ábendingunni var lokað þann</label><p>" . strftime('%d. %B %Y klukkan %H:%M', $form['#node']->field_indication_closed_at[LANGUAGE_NONE][0]['value']) . "</p> </p></div>";
          $form['#group_children']['closed_at_markup'] = "group_indication_timestamps";
        }
      }
    }

    $form['#attached']['js'] = array(
      'https://js.arcgis.com/3.13/init.js' => array(
        'type' => 'external',
      ),
      drupal_get_path('module', 'rvk_ticketing') . '/js/map_for_indications.js',
      drupal_get_path('module', 'rvk_ticketing') . '/js/indication.js',
    );

    $arg = arg(2);
    $arg = substr($arg, 0, 4);
    if(($form_id == 'indications_node_form') && ($arg == 'edit')){
      drupal_goto('/abendingar/breyta-abendingu/' . $form['nid']['#value']);
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function rvk_ticketing_node_presave($node) {
  if($node->type == 'indications') {
    //If the indication is being sent to external department (as configured in a taxonomy), we'll just close the
    //Indication
    if(isset($node->field_forward_to_external_dp[LANGUAGE_NONE][0])) {
      if(isset($node->field_forward_to_external_dp[LANGUAGE_NONE][0]['tid'])) {
        $indication_status_voc = taxonomy_vocabulary_machine_name_load('indication_status');
        $indication_tax = _rvk_ticketing_find_indication_status_by_name($indication_status_voc->vid, 'Lokið');
        $node->field_indication_status_ref[LANGUAGE_NONE][0]['tid'] = $indication_tax->tid;
      }
    }

    //If there is text in the indication response, we'll create a new timestamp and log the time it was answered.
    if(isset($node->field_indication_response[LANGUAGE_NONE][0])) {
      if(!isset($node->field_indication_responded_at[LANGUAGE_NONE][0])) {
        $node->field_indication_responded_at[LANGUAGE_NONE][0]['value'] = time();
      }
    }

    //If there is a timestamp for when the indication was answered for the first time, we need to calculate when the
    //indication has to be closed completely
    if(isset($node->field_indication_responded_at[LANGUAGE_NONE][0])) {
      if(!isset($node->field_indication_close_by[LANGUAGE_NONE][0])) {
        if(isset($node->field_indication_type_ref[LANGUAGE_NONE][0])) {
          $indication_category = taxonomy_term_load($node->field_indication_type_ref[LANGUAGE_NONE][0]['tid']);

          $second_response_time = strtotime(rvk_ticketing_get_last_response_date(
            new DateTime('now'), $indication_category->field_indication_response_time[LANGUAGE_NONE][0]['value']
          )->format('Y-m-d H:i'));
        }
        else {
          $second_response_time = strtotime(rvk_ticketing_get_last_response_date(
            new DateTime('now'), 2
          )->format('Y-m-d H:i'));
        }

        $node->field_indication_close_by[LANGUAGE_NONE][0]['value'] = $second_response_time;
      }
    }

    //If the indication is closed, we need to record that timestamp, and also fill inn all the other timestamps that
    //are missing (e.g. if the indication is closed right away).
    if(isset($node->field_indication_status_ref[LANGUAGE_NONE][0])) {
      $status_term = taxonomy_term_load($node->field_indication_status_ref[LANGUAGE_NONE][0]['tid']);
      if($status_term->name == "Lokið") {
        if(!isset($node->field_indication_respond_by[LANGUAGE_NONE][0])) {
          $node->field_indication_respond_by[LANGUAGE_NONE][0]['value'] = strtotime(rvk_ticketing_get_last_response_date(
            new DateTime('now'), 2
          )->format('Y-m-d H:i'));
        }
        if(!isset($node->field_indication_responded_at[LANGUAGE_NONE][0])) {
          $node->field_indication_responded_at[LANGUAGE_NONE][0]['value'] = time();
        }
        if(!isset($node->field_indication_close_by[LANGUAGE_NONE][0])) {
          $node->field_indication_close_by[LANGUAGE_NONE][0]['value'] = strtotime(rvk_ticketing_get_last_response_date(
            new DateTime('now'), 2
          )->format('Y-m-d H:i'));
        }
        if(!isset($node->field_indication_closed_at[LANGUAGE_NONE][0])) {
          $node->field_indication_closed_at[LANGUAGE_NONE][0]['value'] = time();
        }
      }
    }
  }
}

/**
 * Was implemented, but all code removed since we stopped supporting Mainmanager API
 * @param $node
 */
function rvk_ticketing_node_validate($node) {

}
/**
 * Implements hook_permission().
 */
function rvk_ticketing_permission() {
  return array(
    'view ticketing content' => array(
      'title' => t('View ticketing content'),
    ),
    'edit ticketing content' => [
      'title' => t('Edit ticketing content'),
    ],
    'administer ticketing content' => array(
      'title' => t('Administer ticketing content'),
    ),
    'administer ticketing settings' => [
      'title' => t('Administer ticketing settings'),
    ]
  );
}

/**
 * Creates a page for the ticket to be displayed on
 *
 * @return array
 */
function rvk_ticketing_create_indication_page() {
  $build = [
    'indication_form' => drupal_get_form('rvk_ticketing_create_ticket_form'),
  ];

  return $build;
}

/**
 * Implements hook_block_info().
 */
function rvk_ticketing_block_info() {
  $blocks['indication_form'] = [
    'info' => 'Ábendingarform',
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function rvk_ticketing_block_view($delta = '') {
  $markup = '';
  if($delta == 'indication_form') {
    $form = drupal_get_form('rvk_ticketing_create_ticket_form');
    $markup .= drupal_render($form);
  }

  $block['content'] = $markup;

  return $block;
}

/**
 * Form for submission of Incident
 *
 * @author Drupalviking (drupalviking@1xinternet.de)
 * @param $form
 * @param $form_state
 * @return mixed
 */
function rvk_ticketing_create_ticket_form($form, &$form_state) {
  $form['#attached']['css'] = [
    'https://js.arcgis.com/3.13/esri/css/esri.css' => [
      'type' => 'external',
    ],
    drupal_get_path('module', 'rvk_ticketing') . '/css/geolocation.css',
    drupal_get_path('module', 'rvk_ticketing') . '/css/create_indication_form_styles.css',
  ];

  $form['indication_fieldset'] = [
    '#type' => 'fieldset',
    '#weight' => 10,
  ];

  $form['indication_fieldset']['indication_text_fieldset'] = [
    '#type' => 'fieldset',
    '#weight' => 10,
  ];

  $form['indication_fieldset']['image_fieldset'] = [
    '#type' => 'fieldset',
    '#weight' => 32,
  ];

  $form['indication_fieldset']['image_fieldset']['pre_markup'] = [
    '#type' => 'markup',
    '#weight' => 1,
    '#markup' => '<h3><span class="toggle-icon"></span>Senda mynd</h3><div class="collapse">'
  ];

  $form['indication_fieldset']['image_fieldset']['post_markup'] = [
    '#type' => 'markup',
    '#weight' => 100,
    '#markup' => '</div>',
  ];

  $form['indication_fieldset']['map_fieldset'] = [
    '#type' => 'fieldset',
    '#weight' => 30,
  ];

  $form['indication_fieldset']['map_fieldset']['pre_markup'] = [
    '#type' => 'markup',
    '#weight' => 1,
    '#markup' => '<h3><span class="toggle-icon"></span>Veldu staðsetningu á korti</h3><div class="collapse">'
  ];

  $form['indication_fieldset']['map_fieldset']['post_markup'] = [
    '#type' => 'markup',
    '#weight' => 100,
    '#markup' => '</div>',
  ];

  $form['indication_fieldset']['map_fieldset']['map'] = [
    '#type' => 'fieldset',
    '#weight' => 20,
  ];

  $form['indication_fieldset']['map_fieldset']['address'] = [
    '#type' => 'fieldset',
    '#weight' => 30,
  ];

  $form['personal_info_fieldset'] = [
    '#type' => 'fieldset',
    '#weight' => 20,
  ];

  $form['indication_fieldset']['markup'] = [
    '#type' => 'markup',
    '#markup' => '<h2>Senda ábendingu</h2><p>Hér geturðu sent ábendingu um hvað sem er. Ábendingin mun berast þjónustuverinu okkar sem svarar strax eða kemur áfram á réttan stað.</p>',
  ];

  $form['indication_fieldset']['indication_text_fieldset']['title'] = [
    '#type' => 'textfield',
    '#title' => 'Titill',
    '#required' => TRUE,
  ];

  $form['indication_fieldset']['indication_text_fieldset']['content'] = [
    '#type' => 'textarea',
    '#title' => 'Efni ábendingar',
    '#required' => TRUE,
  ];

  $form['indication_fieldset']['image_fieldset']['image_1'] = [
    '#type' => 'managed_file',
    '#title' => 'Mynd',
    '#description' => 'Sendu inn mynd með tilkynningunni, til að gera betri grein fyrir henni',
    '#upload_location' => 'public://indication_images/',
    '#weight' => 50,
  ];

  $form['indication_fieldset']['image_fieldset']['image_2'] = [
    '#type' => 'managed_file',
    '#title' => 'Mynd',
    '#description' => 'Sendu inn mynd með tilkynningunni, til að gera betri grein fyrir henni',
    '#upload_location' => 'public://indication_images/',
    '#weight' => 50,
  ];

  $form['indication_fieldset']['image_fieldset']['image_3'] = [
    '#type' => 'managed_file',
    '#title' => 'Mynd',
    '#description' => 'Sendu inn mynd með tilkynningunni, til að gera betri grein fyrir henni',
    '#upload_location' => 'public://indication_images/',
    '#weight' => 50,
  ];

  $form['indication_fieldset']['image_fieldset']['image_4'] = [
    '#type' => 'managed_file',
    '#title' => 'Mynd',
    '#description' => 'Sendu inn mynd með tilkynningunni, til að gera betri grein fyrir henni',
    '#upload_location' => 'public://indication_images/',
    '#weight' => 50,
  ];

  $form['indication_fieldset']['map_fieldset']['markup_location'] = [
    '#type' => 'markup',
    '#markup' => '<p>Þú getur slegið inn heimilisfang eða sett punkt á kortið með því að smella á þann stað á kortinu sem tengist ábendingunni. Ef þú ert í snjallsíma geturðu virkjað staðsetninguna þína með því að ýta á <span class="locate-icon"></span> hnappinn á kortinu.</p>',
    '#weight' => 21,
  ];

  $form['indication_fieldset']['map_fieldset']['map']['map_markup'] = [
    '#type' => 'markup',
    '#prefix' => '<div id="mapDiv">',
    '#postfix' => '</div>',
    '#markup' => '<div id="LocateButton"></div>',
    '#weight' => 20,
  ];

  $form['indication_fieldset']['map_fieldset']['address']['address'] = [
    '#type' => 'textfield',
    '#title' => 'Staðsetning (Götuheiti í nefnifalli)',
    '#autocomplete_path' => 'gata/fletta_upp_gotu_autocomplete_callback',
    '#weight' => 10,
  ];



  $form['indication_fieldset']['map_fieldset']['xcoords'] = [
    '#type' => 'hidden',
    '#title' => 'xcoords',
    '#attributes' => [
      'id' => ['xcoords']
    ],
  ];

  $form['indication_fieldset']['map_fieldset']['ycoords'] = [
    '#type' => 'hidden',
    '#title' => 'ycoords',
    '#attributes' => [
      'id' => ['ycoords']
    ],
  ];



  $form['personal_info_fieldset']['markup'] = [
    '#type' => 'markup',
    '#markup' => '<h2>Viltu fylgjast með ábendingunni?</h2><p>Ef þú vilt vita hvað verður um ábendinguna þína er nauðsynlegt að fylla þessa reiti út. Ef ekki geturðu smellt á senda hnappinn hér að neðan.</p>',
  ];

  $form['personal_info_fieldset']['name'] = [
    '#type' => 'textfield',
    '#title' => 'Nafn',
  ];

  $form['personal_info_fieldset']['ssn'] = [
    '#type' => 'textfield',
    '#title' => 'Kennitala',
  ];

  $form['personal_info_fieldset']['email'] = [
    '#type' => 'textfield',
    '#title' => 'Netfang',
  ];

  $form['personal_info_fieldset']['tel'] = [
    '#type' => 'textfield',
    '#title' => 'Sími',
  ];

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Senda',
    '#weight' => 200,
  );

  $form['#attached']['js'] = array(
    'https://js.arcgis.com/3.13/init.js' => array(
      'type' => 'external',
    ),
    drupal_get_path('module', 'rvk_ticketing') . '/js/geolocation.js',
    drupal_get_path('module', 'rvk_ticketing') . '/js/indication.js',
  );

  return $form;
}

/**
 * Implements hook_form_validate().
 */
function rvk_ticketing_create_ticket_form_validate($form, &$form_state) {
  $values = $form_state['values'];

  if(strlen($values['address']) > 0) {
    if(!rvk_ticket_check_street_address_valid($values['address'])) {
      form_set_error('address', 'Svo virðist sem ekki hafi verið valið rétt heimilisfang.');
    }
  }

  if(strlen($values['ssn']) > 0) {
    if(!_rvk_ticketing_ssn_validation($values['ssn'])) {
      form_set_error('ssn', 'Kennitalan virðist ekki vera rétt, vinsamlegast athugið hana.');
    }
  }
}

/**
 * Checks to see if the address entered is valid, by looking up the address name
 * at Borgarvefsja API
 *
 * @param string $address The Address to validate
 * @return bool
 */
function rvk_ticket_check_street_address_valid($address) {
  $street = borgarvefsja_search_by_address($address);
  return($street[0]['text'] != $address) ? false : true;
}

/**
 * Implements hook_form_submit().
 *
 * Since it's a multistep form, validations on where the user is in it, are in
 * place.
 */

function rvk_ticketing_create_ticket_form_submit($form, &$form_state) {
  $values = $form_state['values'];

  if($values['image_1']) {
    $file = file_load((int)$values['image_1']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $values['image_1'] = $file;
  }

  if($values['image_2']) {
    $file = file_load((int)$values['image_2']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $values['image_2'] = $file;
  }

  if($values['image_3']) {
    $file = file_load((int)$values['image_3']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $values['image_3'] = $file;
  }

  if($values['image_4']) {
    $file = file_load((int)$values['image_4']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $values['image_4'] = $file;
  }

  if(strlen($values['xcoords']) == 0 && strlen($values['ycoords']) == 0 && strlen($values['address']) > 0) {
    //Send another query to the Street lookup API, to get the X and Y coords
    $street = borgarvefsja_search_by_address($values['address']);
    $values['xcoords'] = $street[0]['x'];
    $values['ycoords'] = $street[0]['y'];
  }

  rvk_ticketing_create_indication_node($values);

  drupal_goto(variable_get('rvk_ticketing_thank_you_page'));
}

/**
 * Creates one indication node, based on the values the user submits.
 *
 * @param array $data The data comes from a form
 * @return \stdClass
 */
function rvk_ticketing_create_indication_node($data) {
  $node = new stdClass();
  $node->title = $data['title'];
  $node->type = 'indications';
  node_object_prepare($node);

  $node->field_indication_text[LANGUAGE_NONE][0]['value'] = $data['content'];
  $node->field_interpered_indication_text[LANGUAGE_NONE][0]['value'] = $data['content'];
  if(isset($data['address'])) {
    $node->field_indication_location[LANGUAGE_NONE][0]['value'] = $data['address'];
    if(isset($data['xcoords'])) {
      $node->field_indication_position_x[LANGUAGE_NONE][0]['value'] = $data['xcoords'];
      $node->field_indication_position_y[LANGUAGE_NONE][0]['value'] = $data['ycoords'];
    }
  }
  elseif(isset($data['xcoords'])) {
    $node->field_indication_position_x[LANGUAGE_NONE][0]['value'] = $data['xcoords'];
    $node->field_indication_position_y[LANGUAGE_NONE][0]['value'] = $data['ycoords'];
  }

  $node->field_indication_reporter_name[LANGUAGE_NONE][0]['value'] = $data['name'];
  $node->field_indication_reporter_ssn[LANGUAGE_NONE][0]['value'] = $data['ssn'];
  $node->field_indication_reporter_email[LANGUAGE_NONE][0]['value'] = $data['email'];
  $node->field_indication_reporter_phone[LANGUAGE_NONE][0]['value'] = $data['tel'];

  $tax_vocabulary = taxonomy_vocabulary_machine_name_load('indication_status');
  $taxonomy = taxonomy_get_tree($tax_vocabulary->vid);
  $status_default_tid = null;
  foreach($taxonomy as $tax) {
    if($tax->name == 'Ný ábending') {
      $status_default_tid = $tax->tid;
    }
  }

  $tax_vocabulary = taxonomy_vocabulary_machine_name_load('departments');
  $taxonomy = taxonomy_get_tree($tax_vocabulary->vid);
  $department_tid = null;
  foreach($taxonomy as $tax) {
    if($tax->name == 'Þjónustuver') {
      $department_tid = $tax->tid;
    }
  }

  if(is_object($data['image_1'])) {
    $node->field_image[LANGUAGE_NONE][]['fid'] = $data['image_1']->fid;
  }

  if(is_object($data['image_2'])) {
    $node->field_image[LANGUAGE_NONE][]['fid'] = $data['image_2']->fid;
  }

  if(is_object($data['image_3'])) {
    $node->field_image[LANGUAGE_NONE][]['fid'] = $data['image_3']->fid;
  }

  if(is_object($data['image_4'])) {
    $node->field_image[LANGUAGE_NONE][]['fid'] = $data['image_4']->fid;
  }

  $node->field_indication_status_ref[LANGUAGE_NONE][0]['tid'] = $status_default_tid;
  $node->field_department_ref[LANGUAGE_NONE][0]['tid'] = $department_tid;
  $node->language = 'is';
  $node->is_new = true;

  try{
    node_save($node);
  }

  catch(exception $e) {

  }

  $respond_by = new DateTime(strftime('%Y-%m-%d %H:%M', $node->created));
  $node->field_indication_respond_by[LANGUAGE_NONE][0]['value'] = strtotime(rvk_ticketing_get_last_response_date($respond_by)->format('Y-m-d H:i'));
  try{
    node_save($node);
  }

  catch(exception $e) {

  }
  return $node;
}

/**
 * Implements hook_views_api().
 */
function rvk_ticketing_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("api" => "3.0");
  }
}


function _rvk_ticketing_find_indication_status_by_name($vid, $status_name) {
  $results = null;
  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $vid)
    ->propertyCondition('name', $status_name, '=')
    ->execute();

  if (!empty($result['taxonomy_term'])) {
    $results = entity_load('taxonomy_term', array_keys($result['taxonomy_term']));
    $results = array_values($results);
    $results = $results[0];
  }

  return $results;
}

/**
 * Implements hook_views_default_views().
 */
function rvk_ticketing_views_default_views() {
  $view = new view();
  $view->name = 'indications';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Ábendingar';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['css_class'] = 'table-layout1';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'show_more';
  $handler->display->display_options['pager']['options']['items_per_page'] = '125';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['pager']['options']['show_more_text'] = 'Sjá allar';
  $handler->display->display_options['pager']['options']['initial'] = '3';
  $handler->display->display_options['pager']['options']['effects']['type'] = 'scroll_fade';
  $handler->display->display_options['pager']['options']['effects']['speed_type'] = 'slow';
  $handler->display->display_options['pager']['options']['effects']['speed'] = 'slow';
  $handler->display->display_options['style_plugin'] = 'table';
  /* Header: Global: Result summary */
  $handler->display->display_options['header']['result']['id'] = 'result';
  $handler->display->display_options['header']['result']['table'] = 'views';
  $handler->display->display_options['header']['result']['field'] = 'result';
  $handler->display->display_options['header']['result']['content'] = '<h2><span class="icon-status"></span>Óhreyfðar ábendingar <span class="total-rows"> (@total)</span></h2>';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Nafn sendanda */
  $handler->display->display_options['fields']['field_indication_reporter_name']['id'] = 'field_indication_reporter_name';
  $handler->display->display_options['fields']['field_indication_reporter_name']['table'] = 'field_data_field_indication_reporter_name';
  $handler->display->display_options['fields']['field_indication_reporter_name']['field'] = 'field_indication_reporter_name';
  /* Field: Content: Post date */
  $handler->display->display_options['fields']['created']['id'] = 'created';
  $handler->display->display_options['fields']['created']['table'] = 'node';
  $handler->display->display_options['fields']['created']['field'] = 'created';
  $handler->display->display_options['fields']['created']['label'] = 'Skráð þann';
  $handler->display->display_options['fields']['created']['date_format'] = 'short';
  $handler->display->display_options['fields']['created']['second_date_format'] = 'long';
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'indications' => 'indications',
  );

  /* Display: Nýjar ábendingar */
  $handler = $view->new_display('block', 'Nýjar ábendingar', 'block');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['defaults']['header'] = FALSE;
  /* Header: Global: Result summary */
  $handler->display->display_options['header']['result']['id'] = 'result';
  $handler->display->display_options['header']['result']['table'] = 'views';
  $handler->display->display_options['header']['result']['field'] = 'result';
  $handler->display->display_options['header']['result']['content'] = '<h2 class="table-layout1__item-count"><span class="icon-circle icon-circle--new"></span><span>Nýjar og óflokkaðar ábendingar </span><span class="total-rows"> (@total)</span></h2>';
  $handler->display->display_options['defaults']['arguments'] = FALSE;

  /* Display: Í vinnslu */
  $handler = $view->new_display('block', 'Í vinnslu', 'block_1');
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: Author */
  $handler->display->display_options['relationships']['uid']['id'] = 'uid';
  $handler->display->display_options['relationships']['uid']['table'] = 'node';
  $handler->display->display_options['relationships']['uid']['field'] = 'uid';
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'indications' => 'indications',
  );

  /* Display: Óhreyfðar ábendingar */
  $handler = $view->new_display('block', 'Óhreyfðar ábendingar', 'block_2');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['defaults']['header'] = FALSE;
  /* Header: Global: Result summary */
  $handler->display->display_options['header']['result']['id'] = 'result';
  $handler->display->display_options['header']['result']['table'] = 'views';
  $handler->display->display_options['header']['result']['field'] = 'result';
  $handler->display->display_options['header']['result']['content'] = '<h2 class="table-layout1__item-count"><span class="icon-circle icon-circle--alert"></span><span>Komnar framyfir svartíma </span><span class="total-rows"> (@total)</span></h2>';
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'indications' => 'indications',
  );
  /* Filter criterion: Content: Updated date */
  $handler->display->display_options['filters']['changed']['id'] = 'changed';
  $handler->display->display_options['filters']['changed']['table'] = 'node';
  $handler->display->display_options['filters']['changed']['field'] = 'changed';
  $handler->display->display_options['filters']['changed']['operator'] = '<=';
  $handler->display->display_options['filters']['changed']['value']['value'] = '-5 days';
  $handler->display->display_options['filters']['changed']['value']['type'] = 'offset';
  $translatables['indications'] = array(
    t('Master'),
    t('more'),
    t('Apply'),
    t('Reset'),
    t('Sort by'),
    t('Asc'),
    t('Desc'),
    t('Items per page'),
    t('- All -'),
    t('Offset'),
    t('« first'),
    t('‹ previous'),
    t('next ›'),
    t('last »'),
    t('Sjá allar'),
    t('<h2><span class="icon-status"></span>Óhreyfðar ábendingar <span class="total-rows"> (@total)</span></h2>'),
    t('Title'),
    t('Nafn sendanda'),
    t('Skráð þann'),
    t('Nýjar ábendingar'),
    t('<h2 class="table-layout1__item-count"><span class="icon-circle icon-circle--new"></span><span>Nýjar og óflokkaðar ábendingar </span><span class="total-rows"> (@total)</span></h2>'),
    t('Í vinnslu'),
    t('author'),
    t('Óhreyfðar ábendingar'),
    t('<h2 class="table-layout1__item-count"><span class="icon-circle icon-circle--alert"></span><span>Komnar framyfir svartíma </span><span class="total-rows"> (@total)</span></h2>'),
  );


  $export['test'] = $view;

  return $export;
}

/**
 * Validates an Icelandic SSN number
 *
 * @param $ssn
 * @return bool
 */
function _rvk_ticketing_ssn_validation($ssn) {
  $sanitised = (string) preg_replace('/[^0-9]/','', $ssn);
  $checksum = substr($sanitised,0,1)*3;
  $checksum += substr($sanitised,1,1)*2;
  $checksum += substr($sanitised,2,1)*7;
  $checksum += substr($sanitised,3,1)*6;
  $checksum += substr($sanitised,4,1)*5;
  $checksum += substr($sanitised,5,1)*4;
  $checksum += substr($sanitised,6,1)*3;
  $checksum += substr($sanitised,7,1)*2;

  $moduloRem = 11-fmod($checksum,11);
  if (($moduloRem == '11') && (substr($sanitised,8,1) === '0')) {
    return true;
  }
  elseif ($moduloRem == 10) {
    return false;
  }
  elseif ($moduloRem == substr($sanitised,8,1)) {
    return true;
  }
  else {
    return false;
  }
}

/**
 * Returns the last day a ticket can be responded to.
 *
 * This algorithm takes into consideration, weekends, opening hours and holidays to determine when the last day is.
 *
 * @param DateTime $day
 * @return DateTime
 */
function rvk_ticketing_get_last_response_date(DateTime $day, $days_to_respond = 2) {
  $last_response_date = $day;

  //Check to see if the service desk is open (hour wise). If it isn't, then add one day
  //to the response time.
  $opening_hour = new DateTime($last_response_date->format('Y-M-d' . ' 08:20'));
  $dateVal = $last_response_date->diff($opening_hour);
  if($dateVal->h >= 8) {
    $last_response_date->modify('+1 day');
    $last_response_date->setTime(8,20);
  }
  elseif($dateVal->h < 0 || $dateVal->invert == 0) {
    $last_response_date->setTime(8,20);
  }

  //Check to see if the day is a holiday. If it is, add one day to the response time.
  if(_rvk_ticketing_is_day_a_holiday($last_response_date)) {
    $last_response_date->modify('+1 day');
  }

  //While we still have some response time left, check to see if the day is a holiday or not.
  //We always add one day to the response, but if it wasn't a holiday, we deduct one day from the
  //total days to respond.
  while($days_to_respond > 0) {
    if(_rvk_ticketing_is_day_a_holiday($last_response_date)) {
      $last_response_date->modify('+1 day');
    }

    else {
      $last_response_date->modify("+1 day");
      $days_to_respond--;
    }
  }

  //After we have deducted all the response days, we'll still have to check if that day is a holiday or not.
  //Therefor we have to go over the holidays once again.
  while(_rvk_ticketing_is_day_a_holiday($last_response_date)) {
    $last_response_date->modify('+1 day');
  }

  return $last_response_date;
}

/**
 * Determines if a day is a holiday (public or official) or not.
 *
 * @param DateTime $day
 * @return bool
 */
function _rvk_ticketing_is_day_a_holiday(DateTime $day) {
  $holidays = _rvk_ticketing_get_holidays_for_year($day->format('Y'), $day->format('H:i'));
  foreach($holidays as $holiday) {
    if( $holiday == $day ) {
      return true;
    }
  }
  if(_rvk_ticketing_is_day_on_a_weekend($day)) {
    return true;
  }

  return false;
}

/**
 * Determines if a day is on a weekend or not
 *
 * @param DateTime $day
 * @return bool
 */
function _rvk_ticketing_is_day_on_a_weekend(DateTime $day) {
  $weekday = $day->format('w');
  if($weekday == 6 || $weekday == 0 )
    return true;
  return false;
}

/**
 * Returns an array of all holidays for a given year
 *
 * @param $year
 * @return array
 */
function _rvk_ticketing_get_holidays_for_year($year, $time) {
  $holidays = [];
  $holidays['new_years_day'] = new DateTime($year . '-01-01 ' . $time);
  $holidays['may_first'] = new DateTime($year . '-05-01 ' . $time);
  $holidays['june_seventeenth'] = new DateTime($year . '-06-17 ' . $time);
  $holidays['christmas_eve'] = new DateTime($year . '-12-24 ' . $time);
  $holidays['christmas_day'] = new DateTime($year . '-12-25 ' . $time);
  $holidays['second_of_xmas'] = new DateTime($year . '-12-26 ' . $time);
  $holidays['new_years_eve'] = new DateTime($year . '-12-31 ' . $time);
  $holidays['maundy_thursday'] = _rvk_ticketing_get_easter_sunday($year, $time)->modify('-3 day');
  $holidays['great_friday'] = _rvk_ticketing_get_easter_sunday($year, $time)->modify('-2 day');
  $holidays['easter_sunday'] = _rvk_ticketing_get_easter_sunday($year, $time);
  $holidays['easter_monday'] = _rvk_ticketing_get_easter_sunday($year, $time)->modify('+1 day');
  $holidays['ascension_of_jesus'] = _rvk_ticketing_get_easter_sunday($year, $time)->modify('+40 day');
  $holidays['petecost'] = _rvk_ticketing_get_easter_sunday($year, $time)->modify('+49 day');
  $holidays['with_monday'] = _rvk_ticketing_get_easter_sunday($year, $time)->modify('+50 day');
  $holidays['first_day_of_summer'] = _rvk_ticketing_get_first_day_of_summer($year, $time);
  $holidays['merchant_holiday'] = _rvk_ticketing_get_merchant_holiday($year, $time);

  return $holidays;
}

/**
 * Returns the date when Easter sunday comes up for given year.
 *
 * Code was aquired here (Python code) and adapted to PHP : https://github.com/solvip/icelandic_holidays/blob/master/icelandic_holidays.py
 *
 * @license MIT
 * @param $year
 * @return DateTime
 */
function _rvk_ticketing_get_easter_sunday($year, $time) {
  $a = $year % 19;
  $b = (int)($year / 100);
  $c = (int)($year % 100);
  $d = (int)($b / 4);
  $e = $b % 4;
  $f = (int)(($b + 8) / 25);
  $g = (int)(($b - $f + 1) / 3);
  $h = (19 * $a + $b -$d -$g + 15) % 30;
  $i = (int)($c / 4);
  $k = $c % 4;
  $l = (32 + 2 * $e + 2 * $i - $h - $k) % 7;
  $m = (int)(($a + 11 * $h + 22 * $l) / 451);
  $month = (int)(($h + $l - 7 * $m +114) / 31);
  $day = ((($h + $l - 7 * $m + 114) % 31) + 1);

  return new DateTime($year . '-' . $month . '-' . $day . ' ' . $time);
}

/**
 * Returns the date for first day of summer in Iceland for any given year
 *
 * The first day of summer is always the third Thursday in April
 *
 * @param $year
 * @return DateTime|static
 */
function _rvk_ticketing_get_first_day_of_summer($year, $time) {
  $day = new DateTime($year . '-04-19 ' . $time);
  while(true) {
    if($day->format('w') == 4) {
      break;
    }
    $day = $day->modify('+1 day');
  }

  return $day;
}

/**
 * Returns the date for the Merchant holiday in Iceland for any given year
 *
 * The Merchant holiday is always the first Monday in August
 *
 * @param $year
 * @return DateTime|static
 */
function _rvk_ticketing_get_merchant_holiday($year, $time) {
  $day = new DateTime($year . '-08-01 ' . $time);
  while(true) {
    if($day->format('w') == 1) {
      break;
    }
    $day = $day->modify('+1 day');
  }

  return $day;
}

/**
 * Implements hook_theme().
 */
function rvk_ticketing_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__indications'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--indications',
    'path' => drupal_get_path('module', 'rvk_ticketing') . '/templates',
  );
  return $theme;
}
